/**
 * Trakerr Client API
 * Get your application events and errors to Trakerr via the *Trakerr API*.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['./generated/src/trakerr/index', 'stacktrace-js'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('./generated/src/trakerr/index'), require('stacktrace-js'), require('error-stack-parser'));
    }
}(function (TrakerrApi, StackTrace, ErrorStackParser) {
    'use strict';

    /**
     * Create a TrakerrClient instance
     *
     * @param apiKey API Key for the application
     * @param url (optional) URL to Trakerr, specify null to use default
     * @param contextAppVersion (optional) application version, defaults to 1.0
     * @param contextEnvName (optional) environment name like "development", "staging", "production" or a custom string
     * @param contextEnvVersion (optional) environment version
     * @param contextEnvHostname (optional) environment hostname, defaults to hostname
     * @param contextAppOS (optional) Operating system
     * @param contextAppOSVersion (optional)  Operating system version
     * @param contextAppBrowser (optional) Browser name
     * @param contextAppBrowserVersion (optional) Browser version
     * @param contextDataCenter (optional) Data center
     * @param contextDataCenterRegion (optional) Data center region
     *
     * @module index
     * @version 1.0.0
     */
    var exports = function TrakerrClient(apiKey,
        contextAppVersion,
        contextEnvName) {
        var _this = this;

        _this.apiKey = apiKey;
        _this.contextAppVersion = contextAppVersion ? contextAppVersion : '1.0';
        _this.contextEnvName = contextEnvName ? contextEnvName : 'development';

        _this.contextEnvVersion = 'undefined';
        _this.contextEnvHostname = 'undefined';
        _this.contextAppOS = 'undefined';
        _this.contextAppOSVersion = 'undefined';
        _this.contextAppBrowser = 'undefined';
        _this.contextAppBrowserVersion = 'undefined';
        _this.contextDataCenter = 'undefined';
        _this.contextDataCenterRegion = 'undefined';

        if (typeof navigator !== 'undefined') {
            _this.contextAppOS = navigator.platform;
            _this.contextAppOSVersion = navigator.oscpu;
            _this.contextAppBrowser = navigator.appCodeName;
            _this.contextAppBrowserVersion = navigator.appVersion;
        } else {
            try {
                var os = require('os');

                if (typeof os !== 'undefined') {
                    _this.contextAppOS = os.platform();
                    _this.contextAppOSVersion = os.release();
                    _this.contextEnvHostname = os.hostname();
                }
            } catch (err) {

            }
        }

        var apiClient = new TrakerrApi.ApiClient();

        _this.eventsApi = new TrakerrApi.EventsApi(apiClient);

        function fillDefaults(appEvent) {
            if (typeof appEvent.apiKey === 'undefined') appEvent.apiKey = _this.apiKey;

            if (typeof appEvent.contextAppVersion === 'undefined') appEvent.contextAppVersion = _this.contextAppVersion;

            if (typeof appEvent.contextEnvName === 'undefined') appEvent.contextEnvName = _this.contextEnvName;
            if (typeof appEvent.contextEnvVersion === 'undefined') appEvent.contextEnvVersion = _this.contextEnvVersion;
            if (typeof appEvent.contextEnvHostname === 'undefined') appEvent.contextEnvHostname = _this.contextEnvHostname;

            if (typeof appEvent.contextAppOS === 'undefined') {
                appEvent.contextAppOS = _this.contextAppOS;
                appEvent.contextAppOSVersion = _this.contextAppOSVersion;
            }

            if (typeof appEvent.contextDataCenter === 'undefined') appEvent.contextDataCenter = _this.contextDataCenter;
            if (typeof appEvent.contextDataCenterRegion === 'undefined') appEvent.contextDataCenterRegion = _this.contextDataCenterRegion;

            if (typeof appEvent.eventTime === 'undefined') appEvent.eventTime = (new Date()).getTime();
            return appEvent;
        }

        function fillStacktrace(error, classification, stackFrames) {
            var type = (typeof error === 'object') ? error.constructor.name : (typeof error).toString();

            var newEvent = _this.createAppEvent(classification ? classification : "Error", type, error.toString());
            newEvent.eventStacktrace = new TrakerrApi.Stacktrace();

            var innerTrace = new TrakerrApi.InnerStackTrace();
            innerTrace.type = type;
            innerTrace.message = error instanceof Error ? error.message : error.toString();
            innerTrace.traceLines = new TrakerrApi.StackTraceLines();

            for (var i in stackFrames) {
                var traceLine = new TrakerrApi.StackTraceLine();
                traceLine.function = stackFrames[i].functionName;
                traceLine.file = stackFrames[i].fileName;
                traceLine.line = stackFrames[i].lineNumber + ":" + stackFrames[i].columnNumber;
                Array.prototype.push.call(innerTrace.traceLines, traceLine);
            }

            Array.prototype.push.call(newEvent.eventStacktrace, innerTrace);
            return newEvent;
        }

        function sendEventFromError(err, classification, shouldDie, callbackFn) {
            StackTrace
                .fromError(err)
                .then(function (stackFrames) {
                    var newEvent = fillStacktrace(err, classification, stackFrames);
                    if (callbackFn) {
                        callbackFn(newEvent);
                    }
                    _this.sendEvent(newEvent, function (error, data, response) {
                        if (error) {
                            console.error('Error Response: ' + error + ', data = ' + data + ', response = ' + JSON.stringify(response));
                        } else {
                            console.log('Response: data = ' + data + ', response = ' + JSON.stringify(response));
                        }
                        if (shouldDie) {
                            process.exit(1);
                        }
                    });
                })
                .catch(function (err) {
                    console.error("Error: " + err);
                    if (shouldDie) {
                        process.exit(1);
                    }
                });
        }

        /**
         * Setup global exception handling
         *
         * @param shouldDie should the process exit on error (applicable to node or other environments, ignored if in browser)
         */
        TrakerrClient.prototype.handleExceptions = function (shouldDie) {
            if (typeof window !== 'undefined') {
                window.onerror = function (msg, file, line, col, error) {
                    var string = msg.toLowerCase();
                    var substring = "script error";
                    if (string.indexOf(substring) > -1) {
                        console.error('Script Error: Script error encountered, see browser console for more.');
                    } else {
                        sendEventFromError(error, "Error", false);
                    }
                }
            } else if (typeof process !== 'undefined') {
                shouldDie = (typeof shouldDie === 'undefined') ? true : shouldDie;
                process.on('uncaughtException', function (err) {
                    sendEventFromError(err, "Error", shouldDie);
                });
            }
        };


        /**
         * Constructs a new {model:AppEvent}
         *
         * @param classification classification like "Error", "Debug", "Warning" or "Info" or a custom string
         * @param eventType event type
         * @param eventMessage event message
         * @returns app event
         */
        TrakerrClient.prototype.createAppEvent = function (classification, eventType, eventMessage) {
            var _this = this;

            if (!classification) classification = "Error";
            if (!eventType) eventType = 'unknown';
            if (!eventMessage) eventMessage = 'unknown';

            return fillDefaults(new TrakerrApi.AppEvent(_this.apiKey, classification, eventType, eventMessage));
        };


        /**
         * Send err to Trackerr with optional callback to populate custom properties
         *
         * @param err the error to send
         * @param classification    classification like "Error", "Debug", "Warning" or "Info" or a custom string
         * @param callbackFn        (optional) callback function that is called with one parameter i.e. the event, so other properties can be populated before the event is sent
         */
        TrakerrClient.prototype.sendError = function (err, classification, callbackFn) {
            sendEventFromError(err, classification, false, callbackFn);
        };

        /**
         * Send event to Trakerr
         *
         * @param appEvent the event to send constructed using {createAppEvent}
         * @param callback the callback accepting the following parameters: error, data, response
         */
        TrakerrClient.prototype.sendEvent = function (appEvent, callback) {
            var _this = this;

            return _this.eventsApi.eventsPost(fillDefaults(appEvent), callback);
        };

        //accessors

        TrakerrClient.prototype.get_ApiKey = function () {
            var _this = this;

            return _this.apiKey;
        };

        TrakerrClient.prototype.set_ApiKey = function (apikey) {
            var _this = this;

            _this.apiKey = apikey;
        };

        TrakerrClient.prototype.get_contextAppVersion = function () {
            var _this = this;

            return _this.contextAppVersion;
        };

        TrakerrClient.prototype.set_contextAppVersion = function (contextappversion) {
            var _this = this;

            _this.contextAppVersion = contextappversion;
        };

        TrakerrClient.prototype.get_contextEnvName = function () {
            var _this = this;

            return _this.contextEnvName;
        };

        TrakerrClient.prototype.set_contextEnvName = function (contextenvname) {
            var _this = this;

            _this.contextEnvName = contextenvname;
        };

        TrakerrClient.prototype.get_contextEnvVersion = function () {
            var _this = this;

            return _this.contextEnvVersion;
        };

        TrakerrClient.prototype.set_contextEnvVersion = function (contextenvversion) {
            var _this = this;

            _this.contextEnvVersion = contextenvversion;
        };

        TrakerrClient.prototype.get_contextEnvHostname = function () {
            var _this = this;

            return _this.contextEnvHostname;
        };

        TrakerrClient.prototype.set_contextEnvHostname = function (contextenvhostname) {
            var _this = this;

            _this.contextEnvHostname = contextenvhostname;
        };

        TrakerrClient.prototype.get_contextAppOS = function () {
            var _this = this;

            return _this.contextAppOS;
        };

        TrakerrClient.prototype.set_contextAppOS = function (contextappos) {
            var _this = this;

            _this.contextAppOS = contextappos;
        };

        TrakerrClient.prototype.get_contextAppOSVersion = function () {
            var _this = this;

            return _this.contextAppOSVersion;
        };

        TrakerrClient.prototype.set_contextAppOSVersion = function (contextapposversion) {
            var _this = this;

            _this.contextAppOSVersion = contextapposversion;
        };

        TrakerrClient.prototype.get_contextAppBrowser = function () {
            var _this = this;

            return _this.contextAppBrowser;
        };

        TrakerrClient.prototype.set_contextAppBrowser = function (contextappbrowser) {
            var _this = this;

            _this.contextAppBrowser = contextappbrowser;
        };

        TrakerrClient.prototype.get_contextAppBrowserVersion = function () {
            var _this = this;

            return _this.contextAppBrowserVersion;
        };

        TrakerrClient.prototype.set_contextAppBrowserVersion = function (contextappbrowserversion) {
            var _this = this;

            _this.contextAppBrowserVersion = contextappbrowserversion;
        };

        TrakerrClient.prototype.get_contextDataCenter = function () {
            var _this = this;

            return _this.contextDataCenter;
        };

        TrakerrClient.prototype.set_contextDataCenter = function (contextdatacenter) {
            var _this = this;

            _this.contextDataCenter = contextdatacenter;
        };

        TrakerrClient.prototype.get_contextDataCenterRegion = function () {
            var _this = this;

            return _this.contextDataCenter;
        };

        TrakerrClient.prototype.set_contextDataCenterRegion = function (contextdatacenterregion) {
            var _this = this;

            _this.contextDataCenterRegion = contextdatacenterregion;
        };
    };

    return exports;
}));
